# Python Summary part 3

### Error handling
- syntax error
- runtime error
- logical error

In [5]:
# syntax error
prin("hello world")

NameError: name 'prin' is not defined

In [4]:
# runtime error
numbers = list(range(5))
numbers

[0, 1, 2, 3, 4]

In [5]:
numbers[10]

IndexError: list index out of range

In [1]:
# logical error
import numpy as np

radius = 5
area_circle = np.pi*radius

# error: area = pi*radius**2
area_circle


15.707963267948966

In [8]:
# try-except

age = float(input("Whats your age?"))
age

'hello'

In [9]:
try:
    age = float(input("Whats your age?"))
    age
    
except ValueError as err:
    print(err)

could not convert string to float: 'hello'


In [13]:
while True:
    try:
        age = float(input("Whats your age?"))
        if not 0 <= age <= 125:
            raise ValueError("Year must be between 0 and 125")
        print(f"You are {age} years old")
        break
    
    except ValueError as err:
        print(err)

Year must be between 0 and 125
Year must be between 0 and 125
could not convert string to float: 'hello'
could not convert string to float: ''
could not convert string to float: ''
could not convert string to float: ''
You are 41.0 years old


### Functions

```
def name(param1, param2, ...): 
    statements 
    ...
    
name(arg1, arg2, ...)
``` 

In [17]:
# x is input parameter
def squarer(x):
    return x**2

squarer(3) # 3 is an argument

9

In [19]:
squares = [squarer(i) for i in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [30]:
def draw_ascii(number_rows = 5): #keyword argument, keyword + assigned value
    for i in range(1, number_rows +1):
        print(i * "x  " + (number_rows - i) * "o  ")
    
draw_ascii()

x  o  o  o  o  
x  x  o  o  o  
x  x  x  o  o  
x  x  x  x  o  
x  x  x  x  x  


In [31]:
draw_ascii(7)

x  o  o  o  o  o  o  
x  x  o  o  o  o  o  
x  x  x  o  o  o  o  
x  x  x  x  o  o  o  
x  x  x  x  x  o  o  
x  x  x  x  x  x  o  
x  x  x  x  x  x  x  


In [36]:
# arbitary arguments , *args

def mean_(*args): #args is a tuple
    sum_ = 0
    for arg in args:
        sum_ += arg    
    return sum_ /len(args)

mean_(1,2,3)

2.0

In [38]:
# keyword arguments, **kwargs

import numpy as np
def simulate_dices(throws=1, dices=2):
    print(np.random.randint(1,7, size = (throws, dices)))

# default arguments
simulate_dices()

[[2 1]]


In [39]:
simulate_dices(1,4)

[[2 6 4 6]]


In [40]:
simulate_dices(3,1)

[[4]
 [4]
 [5]]


In [41]:
simulate_dices(throws=5)

[[5 2]
 [3 1]
 [6 4]
 [6 5]
 [2 3]]


In [43]:
simulate_dices(dices=3)

[[4 4 3]]


In [44]:
simulate_dices(dices=5, throws=3)

[[5 4 4 4 4]
 [2 2 5 5 5]
 [4 6 2 4 6]]


In [45]:
options = {"dices":3, "throws":3}

simulate_dices(**options)

[[6 3 3]
 [1 1 4]
 [6 1 1]]


In [46]:
option_list = [1,5]

simulate_dices(*option_list)

[[6 1 2 4 4]]


lambda function

In [47]:
# def f(x): 
#   return x**3

f = lambda x: x**3 
f(3)

27

In [52]:
# list of tuples
students = [("Bob", 92), ("Charlie", 78), ("David", 95), ("Alice", 85)]
students

[('Bob', 92), ('Charlie', 78), ('David', 95), ('Alice', 85)]

In [53]:
sorted(students)

[('Alice', 85), ('Bob', 92), ('Charlie', 78), ('David', 95)]

In [54]:
sorted(students, key = lambda student: student[1], reverse=True)

[('David', 95), ('Bob', 92), ('Alice', 85), ('Charlie', 78)]

### Matplolib

### Numpy

### File handling

### Datetime